language: php

sudo: require

php:
  - "7.1"
  - "7.2"

services:
  - docker

before_install:
  - docker pull selenium/standalone-chrome
  - docker run -d -P -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug
  - docker ps -a
  - php -S 8.35.192.0.8080 -t $PWD &
  - composer selfupdate

install:
  - composer install --no-interaction --prefer-source
